### ISSUE TITLE
[BUG] ENV postinstall script doesn't work on Windows

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-dispatcher#117]
### Current behavior

Try to debug to see why the `postinstall` script doesn't correctly generate `CDS_ENV` for me and doesn't compile it.
Here is what I get on Windows 10:

**Command:** cds
**Result:**
```
{
  error: Error: spawnSync cds ENOENT
      at Object.spawnSync (node:internal/child_process:1124:20)
      at spawnSync (node:child_process:877:24)
      at _class.executeShellCommand (node_modules\@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:103:45)
      at _class.generateEnvFile (node_modules\@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:45:31)
      at _class.run (node_modules\@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:116:12)
      at PostInstall2.run (node_modules\@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:135:23)
      at Object.<anonymous> (node_modules\@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:138:19)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
      at Module.load (node:internal/modules/cjs/loader:1288:32) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawnSync cds',
    path: 'cds',
    spawnargs: [ 'env', 'get' ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

**Command:** npx tsc
**Result:**
```
{
  error: Error: spawnSync npx tsc ENOENT
      at Object.spawnSync (node:internal/child_process:1124:20)
      at spawnSync (node:child_process:877:24)
      at _class.executeShellCommand (@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:103:45)
      at _class.compileEnvFile (@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:54:10)
      at _class.run (@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:117:12)
      at PostInstall2.run (@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:135:23)
      at Object.<anonymous> (@dxfrontier\cds-ts-dispatcher\postinstall\PostInstall.js:138:19)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
      at Module.load (node:internal/modules/cjs/loader:1288:32) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawnSync npx tsc',
    path: 'npx tsc',
    spawnargs: [
      'C:\\Users\\PC1\\WebstormProjects\\cds-ts-samples\\@dispatcher\\index.ts',
      '--outDir',
      'C:\\Users\\PC1\\WebstormProjects\\cds-ts-samples\\@dispatcher'
    ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

### Expected behavior

`CDS_ENV` is generated and transpiled.

### Steps to reproduce

Try to install `cds-ts-dispatcher` on Windows.

### Environment

- **@dxfrontier packages**:
"@dxfrontier/cds-ts-dispatcher": "3.2.2",
"@dxfrontier/cds-ts-repository": "4.0.0",
- **node** v20.18.0
- **npm** 10.9.0

### Additional Info

Getting this working is not a priority for me, but, if you have access to Windows machine, would be nice if this could fixed.

**Comment by hakimio** [comment]
Yes, both `cds env` and `npx tsc` works normally and are installed globally.

**Comment by dragolea** [comment]
Ok, looks like it's about Windows 10, have you tried on `Windows 11` or latest version ?

```yml
strategy:
      matrix:
        version: [20, 18]
        platform: [ubuntu-latest, windows-latest, macos-latest]
```

I am doing a strategy matrix and checking the following and for me worked, but I didn't checked on windows 10

**Comment by hakimio** [comment]
Tested with just `npm install`.
BTW, when running `npx tsc` command manually, noticed that I have to add `--skipLibCheck`. Otherwise I get missing `mocha` dependency error.

**Comment by dragolea** [comment]
You use `tsc` for building the `gen/srv/sev` ?

can you try [Deploy cds-ts-dispatcher](https://github.com/dxfrontier/cds-ts-dispatcher?tab=readme-ov-file#deployment-to-btp-using-mta)

**Comment by hakimio** [comment]
Which script/command exactly do you want me to try to run? `"build:ts": "tsc"`? `mbt build`?
The demo app doesn't compile right now because of `CDS_ENV`:
```
 npm run build:ts

> cds-ts-samples@1.0.0 build:ts
> tsc

srv/controller/cat-service/handler/BookHandler.ts:105:19 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

105     @Env<CDS_ENV>('requires.auth.users') users: any[],
                      ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in srv/controller/cat-service/handler/BookHandler.ts:105
```

**Comment by hakimio** [comment]
Anyway, this is not very important for me personally. Just wanted to let you know. So, no rush. Feel free to look into this when you have time and access to Windows 10 machine.

**Comment by dragolea** [comment]
Appreciate, like always your input ! :)

**Comment by dragolea** [comment]
yes, I am having a look over cross-spawn :) 
Which option you've used the cross-spawn or shell: true ?

If you have time, you can create a PR defently :)

**Comment by hakimio** [comment]
I only tested with `shell: true`.

**Comment by dragolea** [comment]
Ok, shell might be a problem on mac, or unix.

**Comment by hakimio** [comment]
Then `cross-spawn` could be a good option too.

**Comment by dragolea** [comment]
ok, I will check `cross-spawn`
Thanks

**Comment by dragolea** [comment]
Fixed in PR #119

**Comment by dragolea** [comment]
Currently the **CDS_ENV** is refresh every time when you _npm install_

**Comment by hakimio** [comment]
Just in general it might be a lot more convenient to manually call a shell script than rely on `npm install` to update the type definition when you change cds config.

Some simple script like the following:
```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

# just use "process.cwd()" instead of `INIT_CWD` to determine current dir
exec node  "$basedir/../@dxfrontier/cds-ts-dispatcher/bin/generate-env.js" "$@"
```

Also, most package managers don't run postinstall scripts if the package or its dependencies don't change.

**Comment by dragolea** [comment]
Ok, understood.
Let's have this as an idea, if you would like to have this please create an issue.
Currently we keep as regenerated on `npm install` and if you think that it would make necessary to have it exposed outside as a `.sh`, defently we can do that.

Thanks for all inputs :)

**Comment by hakimio** [comment]
Thank you for creating and maintaining this awesome library 🙂
