### ISSUE TITLE
[FEATURE] Add support for `cds v8`

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-dispatcher#85]
### Description

`cds v8` has been [officially released](https://cap.cloud.sap/docs/releases/jun24).

Some notable changes:
- `@cap-js/cds-types` types are [no longer re-exported by `@sap/cds`](https://cap.cloud.sap/docs/releases/jun24#typescript). The package has to be installed separately.
- [New odata adapter](https://cap.cloud.sap/docs/releases/jun24#new-protocol-adapters-ga)
- [`ieee754compatible` option](https://cap.cloud.sap/docs/releases/jun24#new-option-cds-features-ieee754compatible) to always output `decimal` and `int64` data as strings.
- [express.js is now optional peer dependency](https://cap.cloud.sap/docs/releases/changelog/#:~:text=express%20is%20now%20an%20optional%20peer%20dependency)

[Full Changelog](https://cap.cloud.sap/docs/releases/changelog/)
[Deprecated Features](https://cap.cloud.sap/docs/releases/jun24#deprecated-features)

### Suggested solution

Release new major version with support for `cds v8`.

**Comment by dragolea** [comment]
hi @hakimio,
Thanks, I will start working on this.

**Comment by dragolea** [comment]
Hi, 
I've opened an issue on the [cds-types issue 145](https://github.com/cap-js/cds-types/issues/145), as somehow the the new version 8 is acting awkard on even the most standard events like `AFTER`.

not sure if you tested version 8 without cds-ts-dispatcher, but looks like is breaking a lot... 

P.S: I've blocked cds-ts-dispatcher & cds-ts-repository currently tu version `7`.

**Comment by hakimio** [comment]
I haven't tested it yet. Was waiting for cds-ts-dispatcher to update.
Anyway, there are no "must have" features for me in `v8`, so I'm fine waiting until the new `cds-types` package issues are resolved.

**Comment by Mischa1610** [comment]
Hi @dragolea I would also be happy to use cds-ts-dispatcher with CDS 8 and could support in testing if needed. (thanks for this good package)
I would assume you would need to wait until your issue https://github.com/cap-js/cds-types/issues/145 is solved, did you had time to check if the PR https://github.com/cap-js/cds-types/pull/151 fixes the issues you have?

**Comment by mvk-abs** [comment]
Hi @Mischa1610.
we didn't try the [#151](https://github.com/cap-js/cds-types/pull/151) yet. As @sap/cds still uses small 'each' we do not assume that with this PR all is resolved. If you like, please comment also on the issue [#145](https://github.com/cap-js/cds-types/issues/145) to put focus on it.

We appreciate that you like our package and salute to your colleagues :)

**Comment by Mischa1610** [comment]
Hi @mvk-abs & @dragolea did you saw that there is a new cds-types release that closes the linked issue:
https://github.com/cap-js/cds-types/pull/184

Would be awesome if you could keep us updated on the "support" of CDS 8 of this package.

**Comment by dragolea** [comment]
Hi @Mischa1610,
Yep, we saw it, we will try very soon, maybe next week to make it working with CDS 8

**Comment by dragolea** [comment]
Hi,

Sorry, we've been catched on some internal projects and we've delayed a bit the migration to V8.
I plan to work on it this week, and next week to have it migrated completly.

Thanks,
Daniel

**Comment by dragolea** [comment]
Hi @Mischa1610 @hakimio, deployed dispatcher with support of CDS V8.
Success

**Comment by hakimio** [comment]
Thank you, Daniel 🙂
