### ISSUE TITLE
[FEATURE] Ability to inject `outboxed` service

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-dispatcher#86]
### Description

Would be nice to be able to directly inject [`outboxed` service](https://cap.cloud.sap/docs/node.js/outbox).
TS types for `cds.outboxed()` were introduced in `cds-types v0.3.0-beta.1`.

### Suggested solution

```ts
    @Inject(CDS_DISPATCHER.OUTBOXED_SRV)
    private readonly outboxedSrv: Service;
```

**Comment by dragolea** [comment]
I've never used this `cds.outboxed`, pls, give me a very sime use case so I know what's all about.

**Comment by hakimio** [comment]
Basically it allows you to:
- save events in your database
- replay/resend them in case of an error
- monitor events for errors
- have truly asynchronous events. The transactions in your event handler will no longer be tied to transactions in your event emitter. If event handler fails, it will not have any effect on event emitter.

**Comment by hakimio** [comment]
Ok, if anyone else wants to use `outboxed()` with `cds v7` and `cds-types v0.2.0`, here is the type definition for `outboxed()`:
```ts
declare module '@sap/cds' {
    export declare const outboxed: (service: Service) => Service;
    export * from '@cap-js/cds-types';
}
```

**Comment by dragolea** [comment]
Ok, just did a small feasability check, and this should not be that hard to implement.
If you follow this feature in the new cds-types package, let me know once it's there and I will start impelemnting it.

**Comment by hakimio** [comment]
The type is already in the new `cds-types` package, starting with `v0.3.0-beta.1`. The only problem is that cds-types `v0.3.0+` is not compatible with `cds v7`.

**Comment by lianas10tb** [comment]
Help me do this
