### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lianas10tb** [dxfrontier/cds-ts-dispatcher#93]

**Comment by Janhouse** [comment]
@dragolea any examples on how to us it with event mesh? Is it even supported?

I mean the


Tried it with  `Repository` and `ExternalService` from `cds-ts-repository`, but it throws some errors (`Cannot read properties of undefined (reading 'drafts')`). 

Meanwhile nothing in `cds-ts-dispatcher` seems to support connecting to the message queue.

**Comment by dragolea** [comment]
Hi @Janhouse,
It would be good to have a new issue created from the **Issues - feature request** for your request as above issue was created by a spammer and closed without notice by us.

Please give us also a little bit more context on your feature request, maybe even a sample repository where you have used this.

Thanks,
Daniel
